### ISSUE TITLE
Differences from appfy.recipe.appengine?

### ISSUE THREAD

**Issue by webmaven** [jensens/collective.recipe.appengine#1]
I see this project is a fork of appfy.recipe.appengine. What are the differences?

**Comment by jensens** [comment]
Overall it was a pragmatic fork. No major differences, but several minor ones. 
At time of writing appfy.recipe.gae just didnt worked with a recent appengine. 
Also it did not work with a at-time-of-writing recent zc.buildout version.
I changed namespaces and unified namings a bit. 
IIRC I also changed the way the addon-libs are included - sorry, its been some time and this was only a side-product of the project. IIRC it was also to simplfiy testing (of the app itself).

Does this answer your question?

**Comment by webmaven** [comment]
Yup, thanks for the reply.

Might be worth putting some of this into the README or a CHANGES file.

**Comment by webmaven** [comment]
Closing.
